export const emptyItem = {
  id: '',
  eventTitle: '',
  eventDescription: '',
  isPeriod: false,
  startYear: '',
  startMonth: '',
  startDay: '',
  startTime: '',
  endYear: '',
  endMonth: '',
  endDay: '',
  endTime: '',
  tagsInString: '',
  tagsInArray: [],
};